---
- name: Ping z/OS node
  hosts: zos
  gather_facts: false
  environment: "{{ environment_vars }}"

  tasks:
   - name: Return all available z/OS facts.
     ibm.ibm_zos_core.zos_gather_facts:
     gather_subset:
      -
     filter: sys
    
  register: zos_facts 

  -name: Print return infomation from previous task
  ansible.builigin.debug:
  var: zos_facts 
  
  -name: Print return info from previous task 
  ansible.builtin.debug: 
  var: lpar_name