---
- name: Ping z/OS node
  hosts: zos
  gather_facts: false
  environment: "{{ environment_vars }}"

  tasks:
   - name: Return all available z/OS facts.
     ibm.ibm_zos_core.zos_gather_facts:
     gather_subset:
      - ipl
      - sys
     filter:
      - "*parmlib*"
  register: result

  -namee: Print return infomation from previous task
  ansible.builigin.debug:
  msg: "The gathered facts are: {{ result }}"