- name: Gather all available z/OS facts
  hosts: zos
  gather_facts: false
  environment: "{{ environment_vars }}"

  tasks:
   - name: Display all stc.
     ibm.ibm_zos_core.zos_job_query:
     
   - name: Display the list of STCs
  var: zos_stc

  -name: print return info from previous task 
  ansible.builtin.debug:
    var: zos_stc